repos:
- repo: https://github.com/fastai/nbdev
  rev: 2.3.34
  hooks:
  - id: nbdev_clean
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.10
  hooks:
  - id: ruff-format
    types_or: [ python, pyi, jupyter ]